/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bytedance_hadoop_io_compress_BroNative_DecodeProgress */

#ifndef _Included_com_bytedance_hadoop_io_compress_BroNative_DecodeProgress
#define _Included_com_bytedance_hadoop_io_compress_BroNative_DecodeProgress
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
